services:
    polidog_laravel.controller.fallback:
        class: Polidog\LaravelBundle\Controller\FallbackController
        arguments:
            - "@polidog_laravel.environment"
            - "@polidog_laravel.laravel_kernel"

    polidog_laravel.environment:
        class: Polidog\LaravelBundle\Environment
        arguments:
            - "%polidog_laravel.env%"

    polidog_laravel.laravel_kernel:
        class: Polidog\LaravelBundle\LaravelKernel
        arguments:
            - "@polidog_laravel.bootstrap"

    polidog_laravel.bootstrap:
        class: Polidog\LaravelBundle\Bootstrap
        arguments:
            - "%polidog_laravel.bootstrap_file%"
